
trigger:
  branches:
    include:
      - main

variables:
  TF_VERSION: '1.7.5'

parameters:
  - name: action
    displayName: 'Terraform Action'
    type: string
    default: 'apply'
    values:
      - apply
      - destroy

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Terraform_Execute
  jobs:
  - job: TerraformJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - script: |
        curl -sL https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
      displayName: 'Install Terraform'

    - checkout: self

    - script: terraform init
      displayName: 'Terraform Init'

    - script: terraform plan -var-file="terraform.tfvars" -out=tfplan
      displayName: 'Terraform Plan'

    - script: |
        if [ "${{ parameters.action }}" == "apply" ]; then
          terraform apply -auto-approve tfplan
        elif [ "${{ parameters.action }}" == "destroy" ]; then
          terraform destroy -var-file="terraform.tfvars" -auto-approve
        else
          echo "Invalid action. Use apply or destroy."
          exit 1
        fi
      displayName: 'Terraform Apply or Destroy'
